services:
  mysql-db:
    container_name: loadconnect-db
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    volumes:
      - loadconnect-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loadconnect
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

volumes:
  loadconnect-db: